version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
