name: dotnet package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
        # No simple reciept to curl it, so, let's just wait
        options: >-
          --health-cmd "sleep 5"
          --health-interval 3s
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.100"
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build --configuration Release --no-restore src
      - name: Test
        if: ${{ !env.ACT }}
        run: dotnet test --no-restore --no-build --configuration Release src
        env:
          # Default storage emulator connection string
          #   https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-shortcut
          TESTS_DEVELOPMENTSTORAGEACCOUNT: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
      - name: Get tag name
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: Build and push the package package
        if: steps.vars.outputs.tag != null
        run: |
          dotnet pack --no-restore --no-build --configuration Release --include-symbols --include-source -p:PackageVersion=${{ steps.vars.outputs.tag }} -o output/${{ steps.vars.outputs.tag }} src
          dotnet nuget push output/${{ steps.vars.outputs.tag }}/*.symbols.nupkg --source "github"
          dotnet nuget push output/${{ steps.vars.outputs.tag }}/*.nupkg --api-key ${{ secrets.NUGET_API_TOKEN }} --source https://api.nuget.org/v3/index.json
